Models/Class.cs
namespace la_mia_pizzeria_static.Models
{
    public class Pizza
    {
    }
}

Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RazorController.cs
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class RazorController : Controller
    {
        public IActionResult Snack()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Pizzeria Anema e Core</h1>
    <div class="row row-cols-5 justify-content-center g-2">
        <div class="col-2">
            <div class="card">
                <img src="https://media.istockphoto.com/id/604829224/photo/margherita-pizza.jpg?s=612x612&w=0&k=20&c=ALD_hdBp_lnlFQfzOp-_yjPtg5Sbq5P1hHGm30t3HYc=" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Margherita</h3>
                    <p class="card-text">Nel giugno 1889 per onorare la Regina d'Italia, Margherita di Savoia, il cuoco Raffaele Esposito della Pizzeria Brandi inventò una pietanza che chiamò proprio Pizza Margherita
                        (con riferimento al fatto che il termine "pizza", allora sconosciuto al di fuori della città partenopea, indicava quasi sempre le torte dolci), 
                        dove i condimenti salati capitatigli tra le mani, pomodoro, mozzarella e basilico, rappresentavano gli stessi colori della bandiera italiana. 
                    </p>
                    <a href="#" class="btn btn-primary">Ordina</a>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="card">
                <img src="https://media.istockphoto.com/id/604829224/photo/margherita-pizza.jpg?s=612x612&w=0&k=20&c=ALD_hdBp_lnlFQfzOp-_yjPtg5Sbq5P1hHGm30t3HYc=" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Ortolana</h3>
                    <p class="card-text">
                        Nel giugno 1889 per onorare la Regina d'Italia, Margherita di Savoia, il cuoco Raffaele Esposito della Pizzeria Brandi inventò una pietanza che chiamò proprio Pizza Margherita
                        (con riferimento al fatto che il termine "pizza", allora sconosciuto al di fuori della città partenopea, indicava quasi sempre le torte dolci),
                        dove i condimenti salati capitatigli tra le mani, pomodoro, mozzarella e basilico, rappresentavano gli stessi colori della bandiera italiana.
                    </p>
                    <a href="#" class="btn btn-primary">Ordina</a>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="card">
                <img src="https://media.istockphoto.com/id/604829224/photo/margherita-pizza.jpg?s=612x612&w=0&k=20&c=ALD_hdBp_lnlFQfzOp-_yjPtg5Sbq5P1hHGm30t3HYc=" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Capricciosa</h3>
                    <p class="card-text">
                        Nel giugno 1889 per onorare la Regina d'Italia, Margherita di Savoia, il cuoco Raffaele Esposito della Pizzeria Brandi inventò una pietanza che chiamò proprio Pizza Margherita
                        (con riferimento al fatto che il termine "pizza", allora sconosciuto al di fuori della città partenopea, indicava quasi sempre le torte dolci),
                        dove i condimenti salati capitatigli tra le mani, pomodoro, mozzarella e basilico, rappresentavano gli stessi colori della bandiera italiana.
                    </p>
                    <a href="#" class="btn btn-primary">Ordina</a>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="card">
                <img src="https://media.istockphoto.com/id/604829224/photo/margherita-pizza.jpg?s=612x612&w=0&k=20&c=ALD_hdBp_lnlFQfzOp-_yjPtg5Sbq5P1hHGm30t3HYc=" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Broccoli e Salsiccia</h3>
                    <p class="card-text">
                        Nel giugno 1889 per onorare la Regina d'Italia, Margherita di Savoia, il cuoco Raffaele Esposito della Pizzeria Brandi inventò una pietanza che chiamò proprio Pizza Margherita
                        (con riferimento al fatto che il termine "pizza", allora sconosciuto al di fuori della città partenopea, indicava quasi sempre le torte dolci),
                        dove i condimenti salati capitatigli tra le mani, pomodoro, mozzarella e basilico, rappresentavano gli stessi colori della bandiera italiana.
                    </p>
                    <a href="#" class="btn btn-primary">Ordina</a>
                </div>
            </div>
        </div>
    </div>

</div>

Views/Razor/Snack.cshtml
@{
    Layout = "_layoutSnack";
}

<h1 class="Titlo">Snack Page</h1>
<h3 class="Sub-titolo mb-4">In questa pagina potrai visualizzare tutti i miei snack</h3>
<div class="snack">
    @{
        <h4 class="mt-2">
            1. Dichiarare una variabile valorizzandola con il nostro nome.
            Dichiarare un'altra variabile valorizzandola con il nostro cognome.
            Stampare il nostro nome e cognome all'interno di un tag h2.
        </h4>
        string nome = "Lorenzo";
        string cognome = "Veropalumbo";

        <h2>Ah. Quasi dimenticavo io mi chiamo @nome @cognome</h2>

        <h4 class="mt-2">
            2. Creare una funzione che stampa la somma dei numeri che vanno da 1 a n (con n passato come parametro - n incluso)
            Stampare dentro uno span il risultato.
        </h4>
        int random = new Random().Next(1, 101);

        for (int i = 0; i <= random; i++)
        {
            if (i == random)
            {
                <span>@i</span>
            }
            else
            {
                <span>@i - </span>
            }
        
        }

        <h4 class="mt-2">
            3. Contare quante volte la lettera a è presente nalla frase "nel mezzo del cammin di nostra vita" e stampare questo valore in pagina
        </h4>
        string frase = "nel mezzo del cammin di nostra vita";
        int j = 0;
    
        foreach(Char lettera in frase){
        
            if(lettera == 'a'){
                j++;
            }
        }

        <h5>la lettera a è presente @j volte nella frase</h5>

        <h4 class="mt-2">
            4. Creare una List<int> di 20 numeri interi (generati random da 1 a 90, 1 e 90 inclusi) e mostrare in pagina solo i numeri compresi tra 20 e 70
        </h4>

        List<int> ListaNumeri = new List<int>(20);
        for (int k = 0; k < 20; k++)
        {
            int random2 = new Random().Next(1, 91);
            ListaNumeri.Add(random2);
            if (random2 > 20 && random2 < 70)
            {
                <span>@random2 </span>
            }
        }

        <h4 class="mt-2">
            5. Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con il formato anno-mese-giorno ore:minuti:secondi
        </h4>

        <span>Data e ora di oggi: @DateTime.Now</span>
    
        <h4 class="mt-2">
            6. Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina <br>
            a. la data di 7 giorni fa <br>
        </h4>

        <h5>La data di 7 gioni fa è : @DateTime.Now.AddDays(-7)</h5>
    
        <h4 class="mt-2">
            b. che giorno della settimana è oggi (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...) <br>
        </h4>

        <h5>Oggi è : @DateTime.Now.ToString("dddd")</h5>

        <h4 class="mt-2">
            c. che giorno della settimana sarà nello stesso giorno e mese di oggi ma tra un anno (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
        </h4>

        <h5>tra un anno oggi sarà : @DateTime.Now.AddYears(1).ToString("dddd")</h5>
    }
</div>

<div><span class="home"><a asp-area="" asp-controller="Home" asp-action="Index">Torna alla home</a></span></div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Razor" asp-action="Snack">Snack</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_layoutSnack.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>